base_packages:
  - epel-release
  - vim
  - git
  - tree
  - lrzsz
  - lsof
  - net-tools
  - openssl-devel
  - wget
  - nc

time_zone: Asia/Manila

ssh_config:
  port: 3333
  disalbe_root_login: False
  disalbe_password_login: False


ssh_pub_key:
  - files/kaka.pub

need_to_stopped_service: firewalld

